hunav_loader:
  ros__parameters:
    yaml_base_name: custom_agents
    simulator: Gazebo Classic
    map: room_box
    publish_people: true
    global_goals:
      1:
        x: 1.10
        y: -4.11
      2:
        x: -1.65
        y: 4.5
      3:
        x: -3.95
        y: 2.51
      4:
        x: 3.80
        y: 0.13
    agents:
      - agent1
      - agent2
    agent1:
      id: 1
      group_id: -1
      skin: 4
      max_vel: 0.6
      radius: 0.05
      goal_radius: 0.15
      cyclic_goals: true
      init_pose:
        x: 2.0
        y: 0.0
        z: -1.0
        h: 0.0
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 4.0
        obstacle_force_factor: 3.0
        social_force_factor: 2.0
        other_force_factor: 5.0
      goals:
        - 1
        - 2
    agent2:
      id: 2
      group_id: -1
      skin: 4
      max_vel: 0.5
      radius: 0.05
      goal_radius: 0.15
      cyclic_goals: true
      init_pose:
        x: 0.0
        y: 2.0
        z: -1.0
        h: -1.57
      behavior:
        type: Regular
        configuration: 0
        goal_force_factor: 4.0
        obstacle_force_factor: 3.0
        social_force_factor: 2.0
        other_force_factor: 5.0
      goals:
        - 3
        - 4